---
title: "A Study of and Recommendation for Revolut"
description: "A study of the potential shortcomings of the neobank Revolut, as well as presentation of a solution."
author: "Aidan Mistry"
date: "2025-14-5"
categories: [Research, Academic, Data Analysis]
---

## Assignment Reflection

As part of the Business Strategy class myself and a group were tasked with analsing a company. For our selection we chose the neobank Revolut. We identified a primary issue as being that the average consumer was not comftorable using a fully digital bank for all their banking needs, and viewed Revolut as an accesory card and bank as opposed to a full fledged financial institution. Through the paper we made recommendations and analysed Revolut's current and potetntial future business paths.


---

## Project Documents

Below is the PDF document of the groups paper oultining Revolut. Click the link below to view or download the full document:

* 📄 **[Revolut Case Study and Recommendation: Click here to view](data/Revolut Case Study and Recommendation.pdf)**
