---
title: "Reflection"
---

## Overview
*During this course I was exposed to a variety of software programs and programs that I enjoyed learning about and I hope my intial knowledge about them will over time grow into several competencies that I can apply to my future career.*

## Key Learnings
### 1. Version Control (Git & GitHub)
* *Learning GitHub has proven to be a very enjoyable experience. As a website and community GitHub and its shared open source code is a very valuable asset. Additionally its version control function is very helpful for potential mistakes or having evidence of work completed with "proof" logged.*

### 2. Static Site Generation (Quarto)
* *Using Quarto to build a website was also a very enjoyable experience. The personal ePortfolio will hopefully in time continue to be expanded to be a page about myself and my accomplishments that can be used to track for myself but also shown to prospective employers.*


## Challenges & Solutions
* **Challenge:** *During this course I had multiple technical issues with my laptop and running software. Ultimately having to delete and re-download multiple softwares.*
* **Solution:** *The solution to this was quite simply perseverance. Taking the time to work through issues and struggle through issues as they arose was the only way for me to progress forward.*

## Moving Forward & Application
* **Critical Self-Assessment:** *I feel that my overall website came together well. However my issues with my corrupted softwares set me back and my website was made on a much shorter time schedule than intended. While I feel it meets criteria for layout and technical specs I had essentially felt behind for the whole course as I struggled through tech issues while juggling other academic obligations*
* **Beyond the Module:** *I hope to continue updating my ePortfolio as my schooling and career continue to progress, potentially turning into something of a personal LinkedIn*